name: Build mobile apps & check tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with: 
        flutter-version: '3.19.0'
    - name: Install dependencies
      run: flutter pub get
    - name: Generate l10n
      run: flutter gen-l10n
    - name: Build apk
      run: flutter build apk
    - name: Build appbundle
      run: flutter build appbundle
  
  build-ios:
    name: Build ios
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - name: Install dependencies
      run: flutter pub get
    - name: Generate l10n
      run: flutter gen-l10n
    - name: Build ios
      run: flutter build ios --release --no-codesign
  
  check-tests:
    name: Check Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      - name: Flutter doctor
        run: flutter doctor
      - name: Get dependencies
        run:  flutter pub get
      - name: Run l10n generation
        run: flutter gen-l10n
      - name: Run tests
        run: flutter test
        
