name: Build ios

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - name: Install dependencies
      run: flutter pub get
    - name: Generate l10n
      run: flutter gen-l10n
    - name: Build ios
      run: flutter build ios --release --no-codesign
